server:
  port: 8088


spring:
  application:
    name: config-server-bus
  cloud:
    config:
      server:
        git:
          uri: /data/spring-cloud/spring-cloud-config/
          searchPaths: /**
          username:
          password:
      label: master
  rabbitmq:
    host: 172.16.11.140
    port: 5672
    username: admin
    password: admin

eureka:
  instance:
    hostname: 172.16.11.150
    ip-address: 172.16.11.150
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port} # eureka 列表显示ip：port
  client:
    serviceUrl:
      defaultZone: http://172.16.11.150:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"





