spring:
  application:
    name: config-client
server:
  port: 8887

eureka:
  instance:
    hostname: 172.16.11.150
    ip-address: 172.16.11.150
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port} # eureka 列表显示ip：port
  client:
    serviceUrl:
      defaultZone: http://172.16.11.150:8761/eureka/